# Generated by Django 4.1.5 on 2023-02-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_remove_comentario_usuario_alter_comentario_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumento',
            options={'ordering': ['usuario', '-fechaPublicacion']},
        ),
    ]
